# Generated by Django 4.0 on 2022-06-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='number',
            new_name='id',
        ),
    ]
