# Generated by Django 4.0 on 2022-07-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_episode_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SpotifyID'),
        ),
    ]
