# Generated by Django 4.0 on 2022-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_alter_episode_spotify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('start_time', models.CharField(max_length=255, verbose_name='開始時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '一時単語',
                'verbose_name_plural': '一時単語',
            },
        ),
        migrations.AddField(
            model_name='word',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='開始時間'),
        ),
    ]
