# Generated by Django 4.0 on 2022-08-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_temporaryword_word_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryWord',
        ),
    ]
