# Generated by Django 4.1.2 on 2022-10-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_delete_temporaryword'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ジョブ名'),
        ),
    ]
