# Generated by Django 4.1.2 on 2022-10-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_episode_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='word_stored',
            field=models.BooleanField(default=False, verbose_name='単語保存済み'),
        ),
    ]
