# Generated by Django 4.1.2 on 2022-12-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_episode_word_stored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='start_time',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='開始時間'),
        ),
    ]
