changelog:
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bugfix
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
